### ISSUE TITLE
[BUG] `trollstore.py` refuses to run.

### ISSUE THREAD

**Issue by VenomousSteam81** [JJTech0130/TrollRestore#40]
When I run `python3 trollstore.py`, I get this message:

```
Traceback (most recent call last):
  File "/home/lizzie/devices/ipad/TrollRestore/trollstore.py", line 9, in <module>
    from pymobiledevice3.cli.cli_common import Command
ImportError: cannot import name 'Command' from 'pymobiledevice3.cli.cli_common' (/home/lizzie/devices/ipad/TrollRestore/venv/lib/python3.13/site-packages/pymobiledevice3/cli/cli_common.py). Did you mean: 'common'?
```

I am on Gentoo, and am using a venv since I can't go without that.

**Comment by rafael-borecki** [comment]
Had success using Python 3.11.9, iOS 16.6.1 and changing the package versions in requirements.txt to:

```
pymobiledevice3==4.13.5
bpylist2==4.1.1
rich==13.8.0
requests==2.32.3
click==8.1.7
```

**Comment by MelanPrince** [comment]
> Had success using Python 3.11.9, iOS 16.6.1 and changing the package versions in requirements.txt to:
> 
> ```
> pymobiledevice3==4.13.5
> bpylist2==4.1.1
> rich==13.8.0
> requests==2.32.3
> click==8.1.7
> ```

it's  working with python-3.12.10.

需要使用 python 3.11或3.12 版本

**Comment by LukeZGD** [comment]
just changing the first line of requirements.txt to `pymobiledevice3<=6.2.0` fixes it (tested on python 3.14.3, so it works on python 3.13 and newer too)

**Comment by Yilmaz4** [comment]
I'm getting this error in Python 3.14.6 with pymobiledevice3<=6.2.0

```
Traceback (most recent call last):
  File "/home/yilmaz/Downloads/TrollRestore_Linux/trollstore.py", line 13, in <module>
    from pymobiledevice3.services.installation_proxy import InstallationProxyService
  File "/home/yilmaz/Downloads/TrollRestore_Linux/venv/lib/python3.14/site-packages/pymobiledevice3/services/installation_proxy.py", line 14, in <module>
    from pymobiledevice3.services.afc import AfcService
  File "/home/yilmaz/Downloads/TrollRestore_Linux/venv/lib/python3.14/site-packages/pymobiledevice3/services/afc.py", line 171, in <module>
    class AfcHeader(DataclassMixin):
    ...<5 lines>...
        _data_offset: int = field(default=0, init=False, metadata={"subcon": Tell})
  File "/home/yilmaz/Downloads/TrollRestore_Linux/venv/lib/python3.14/site-packages/pymobiledevice3/services/afc.py", line 172, in AfcHeader
    magic: bytes = csfield(Const(AFCMAGIC))
                   ~~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/yilmaz/Downloads/TrollRestore_Linux/venv/lib/python3.14/site-packages/construct_typed/dataclass_struct.py", line 58, in csfield
    raise DataclassFieldError(
        "Fields that can build from None, should be used with ``csfield_noinit()``, ``csfield_default()`` or ``csfield_const()``."
    )
construct_typed.dataclass_struct.DataclassFieldError: Fields that can build from None, should be used with ``csfield_noinit()``, ``csfield_default()`` or ``csfield_const()``.
```

**Comment by CousTov** [comment]
On Arch, make sure you got these installed: libimobiledevice and usbmuxd. (Depending on the system, the package name might be different) Check the status of usbmuxd, make sure that it is running.

replace the requirements.txt with this:
 
pymobiledevice3==4.13.5
bpylist2==4.1.1
rich==13.8.0
requests==2.32.3
click==8.1.7

Then create a venv,
activate the venv,
execute `pip3 install -r requirements.txt `
connect your iPhone, trust the computer
then finally execute `python3 trollstore.py`
